### ISSUE TITLE
TypeError at /admin/  Field 'id' expected a number but got <SimpleLazyObject: <User: jayvdb@gmail.com>>.

### ISSUE THREAD

**Issue by jayvdb** [relip/django-model-repr#3]
Possibly because I am using Django 3.., or something to do with my swappable user model, or could be debug_toolbar or social auth ..

```py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1772, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/usr/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3.8/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    template_rendered.send(sender=self, template=self, context=context)
  File "/usr/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 173, in send
    return [
  File "/usr/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/lib/python3.8/site-packages/debug_toolbar/panels/templates/panel.py", line 104, in _store_template_info
    if isinstance(value, http.HttpRequest):
  File "/usr/lib/python3.8/site-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/usr/lib/python3.8/site-packages/django/utils/functional.py", line 360, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/lib/python3.8/site-packages/social_django/context_processors.py", line 32, in <lambda>
    return {'backends': LazyDict(lambda: user_backends_data(request.user,
  File "/usr/lib/python3.8/site-packages/social_core/backends/utils.py", line 77, in user_backends_data
    associated = storage.user.get_social_auth_for_user(user)
  File "/usr/lib/python3.8/site-packages/social_django/storage.py", line 122, in get_social_auth_for_user
    qs = cls.objects.filter(user=user)
  File "/usr/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1350, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1311, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/usr/lib/python3.8/site-packages/django/db/models/lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/usr/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <User: jayvdb@gmail.com>>.
```

**Comment by jayvdb** [comment]
I disable debug toolbar (v2.2) and it goes away.

**Comment by jayvdb** [comment]
Still occurs on debug toolbar master, goes away when TemplatesPanel is disabled, and looks like https://github.com/jazzband/django-debug-toolbar/issues/1136 is the same problem.

**Comment by relip** [comment]
Thanks for the info -- will look into this on the weekend

**Comment by jayvdb** [comment]
I ended up creating my own at https://github.com/jayvdb/django-dunder , with a hat tip at the bottom for your project.
